[project]
name = "api"
version = "0.1.0"
description = "Python task scheduler Djagno REST API."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.1.4",
    "django-filter>=24.3",
    "djangorestframework>=3.15.2",
    "markdown>=3.7",
    "ruff>=0.8.4",
]
